"use client";
import {useEffect,useState} from "react";
import type {AnalysisResult} from "./analyzer";

type SavedReport={id:string;bankName:string;accountName:string;period:string;resultJson:string;createdAt:number};

export function BankReconciliationTools({result}:{result:AnalysisResult}){
  const [bankName,setBankName]=useState("بنك الراجحي"),[accountName,setAccountName]=useState("الحساب الرئيسي"),[period,setPeriod]=useState(()=>new Date().toISOString().slice(0,7)),[items,setItems]=useState<SavedReport[]>([]),[status,setStatus]=useState("");
  async function load(){try{const response=await fetch("/api/reconciliations"),data=await response.json() as {items?:SavedReport[]};setItems(data.items||[])}catch{setStatus("تعذر تحميل التقارير المحفوظة")}}
  useEffect(()=>{void load()},[]);
  async function save(){setStatus("جارٍ الحفظ...");try{const response=await fetch("/api/reconciliations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({bankName,accountName,period,result})}),data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||"تعذر الحفظ");setStatus("تم حفظ المطابقة الشهرية ✓");await load()}catch(error){setStatus(error instanceof Error?error.message:"تعذر الحفظ")}}
  async function remove(id:string){await fetch(`/api/reconciliations?id=${encodeURIComponent(id)}`,{method:"DELETE"});await load()}
  function printRecord(){document.body.classList.add("printing-bank-record");const clean=()=>document.body.classList.remove("printing-bank-record");window.addEventListener("afterprint",clean,{once:true});window.print();window.setTimeout(clean,1500)}
  const summary=(label:string)=>result.summary.find(item=>item.label===label)?.value||"—",created=new Intl.DateTimeFormat("ar-SA",{dateStyle:"long"}).format(new Date());
  return <section className="bank-tools"><div className="bank-tools-head"><div><span>المطابقة الشهرية ومحضر الاعتماد</span><h3>حفظ وطباعة مطابقة البنك</h3><p>احفظ التقرير باسم البنك والحساب والفترة، أو اطبع المحضر الرسمي بصيغة PDF.</p></div><div className="bank-tool-actions"><button onClick={printRecord}>طباعة محضر PDF</button><button className="primary" onClick={save}>حفظ المطابقة الشهرية</button></div></div><div className="bank-save-form"><label>البنك<select value={bankName} onChange={event=>setBankName(event.target.value)}><option>بنك الراجحي</option><option>بنك ساب</option><option>شبكة الراجحي</option><option>شبكة ساب</option></select></label><label>اسم/رقم الحساب<input value={accountName} onChange={event=>setAccountName(event.target.value)}/></label><label>الفترة<input type="month" value={period} onChange={event=>setPeriod(event.target.value)}/></label></div>{status&&<div className="bank-save-status">{status}</div>}<div className="saved-reconciliations"><div><b>التقارير المحفوظة</b><span>{items.length} تقرير</span></div>{items.length?<ul>{items.slice(0,8).map(item=><li key={item.id}><button onClick={()=>{const saved=JSON.parse(item.resultJson) as AnalysisResult;const text=[saved.title,...saved.summary.map(x=>`${x.label}: ${x.value}`)].join("\n");navigator.clipboard.writeText(text);setStatus("تم نسخ ملخص التقرير المحفوظ ✓")}}><strong>{item.bankName} · {item.accountName}</strong><small>{item.period} · {new Intl.DateTimeFormat("ar-SA").format(new Date(item.createdAt))}</small></button><button className="delete-saved" aria-label="حذف التقرير" onClick={()=>remove(item.id)}>×</button></li>)}</ul>:<p>لم يتم حفظ مطابقة شهرية بعد.</p>}</div><div className="bank-record"><img src="/mazaya-letterhead.jpg" alt=""/><div className="bank-record-content"><div className="record-date">التاريخ: {created}</div><h1>محضر مطابقة حساب بنكي</h1><p>البنك: <b>{bankName}</b></p><p>الحساب: <b>{accountName}</b></p><p>الفترة: <b>{period}</b></p><div className="record-grid"><span>الرصيد الافتتاحي بالبنك<b>{summary("الرصيد الافتتاحي بالبنك")}</b></span><span>الرصيد الختامي بالبنك<b>{summary("الرصيد الختامي بالبنك")}</b></span><span>الرصيد الختامي بالنظام<b>{summary("الرصيد الختامي بالنظام")}</b></span><span>فرق الرصيد<b>{result.conclusion?.value||"—"}</b></span></div><h2>نتيجة المطابقة</h2><p>{result.conclusion?.detail}</p><p>الحركات المطابقة: <b>{summary("حركات مطابقة")}</b> · المطابقات المجمعة: <b>{summary("مطابقات مجمعة")}</b> · بالبنك فقط: <b>{summary("بالبنك فقط")}</b> · بالنظام فقط: <b>{summary("بالنظام فقط")}</b>.</p><div className="record-note">هذا المحضر تقرير مراجعة، وأي قيد تسوية وارد فيه مقترح فقط ولا يتم ترحيله تلقائيًا.</div><div className="record-signatures"><span>إعداد المحاسب<br/><br/>الاسم والتوقيع</span><span>المراجعة<br/><br/>الاسم والتوقيع</span><span>اعتماد المدير<br/><br/>الاسم والتوقيع</span></div></div></div></section>
}
