"use client";
import {useEffect,useRef,useState} from "react";
import {analyzeData,readAccountingFile,type AnalysisResult} from "./analyzer";
import {BalanceConfirmationButton} from "./balance-confirmation";
import {BankReconciliationTools} from "./bank-reconciliation-tools";

const actions=[
 ["مطابقة كشف البنك","ارفع كشف البنك ودفتر الأستاذ لتحديد الفروق وأول نقطة اختلاف","⇄"],
 ["تحليل حساب عميل","الفواتير والتحصيل والرصيد وأعمار 0–30 حتى أكثر من 120 يومًا من تاريخ الإصدار","♙"],
 ["تحليل حساب مورد","المشتريات والمدفوعات والرصيد المستحق وكشف الفروق","♟"],
 ["مطابقة كشف المورد مع حسابنا","ارفع كشف المورد أولًا ثم كشف حسابه من ERP لإظهار كل الفروقات","⇄"],
 ["أعمار الديون والاستحقاق","من تاريخ إصدار الفاتورة: 0–30، 31–45، 46–60، 61–90، 91–120، وأكثر من 120 يومًا","◷"],
 ["مطابقة شبكة الراجحي","قارن مبيعات نقاط البيع مع الإيداعات والعمولات","▣"],
 ["مطابقة شبكة ساب","اكتشف الإيداعات الناقصة أو المجمعة والمتأخرة","▣"],
 ["مراجعة ميزان المراجعة","افحص توازن المدين والدائن والحسابات غير الطبيعية","≡"],
 ["تحليل قيود اليومية","افحص التوازن والتكرار والبيانات الناقصة والمبالغ غير المعتادة دون تعديل القيود","⧉"],
 ["مراجعة المبيعات والضريبة","طابق الفواتير والمرتجعات وضريبة القيمة المضافة","٪"],
 ["مراجعة المشتريات","كشف الفواتير المفقودة والمكررة وأرصدة الموردين","▤"],
 ["مطابقة الجرد الفعلي مع النظام","ارفع الجرد الفعلي وتقرير المخزون لاستخراج العجز والزيادة وقيمة الفروق","▦"],
 ["مقارنة حركة الأصناف","راجع أول المدة والمشتريات والمبيعات والمرتجعات وحدد مصدر فرق كل صنف","⇅"],
 ["الربحية الشهرية","اعرف كل شهر ربحنا أم خسرنا مع الهامش والمقارنة","↗"],
 ["تحليل القوائم المالية","المركز المالي والدخل والتغيرات في حقوق الملكية","▥"],
 ["تحليل الميزانية","الأصول والالتزامات والسيولة ورأس المال والمؤشرات","◈"],
 ["التدفقات النقدية","تشغيلي واستثماري وتمويلي ومصادر استخدام النقد","≈"],
 ["مراجعة ضريبة القيمة المضافة","مطابقة المبيعات والمشتريات والإقرارات والفروق","٪"],
 ["مراجعة الزكاة","تحليل الوعاء والعناصر المؤثرة وتجهيز مسودة المراجعة","ز"],
 ["الأصول والإهلاك","سجل الأصول والإضافات والاستبعادات ومجمع الإهلاك","◇"],
 ["الرواتب والعهد","مطابقة الرواتب والتأمينات والسلف وعهد الموظفين","♧"],
 ["تحليل النشاط التجاري","الربحية والسيولة والدوران والمخاطر ونقاط التحسين","◎"],
];
const side=["مراجعة شاملة لكل الحسابات","البنوك والشبكات والصندوق","العملاء وأعمار الديون","الموردون والاستحقاقات","المبيعات والمشتريات","المخزون والتكلفة","القيود وميزان المراجعة","القوائم والميزانيات","الضريبة والزكاة","المصروفات والربحية","التقارير المحفوظة"];
const prompts=["حلّل كشف حساب المورد وحدد الرصيد المستحق","طابق كشف المورد مع حسابنا وأظهر الفروقات","صنّف رصيد العميل 0–30 و31–45 و46–60 و61–90 و91–120 وأكثر من 120 يومًا من تاريخ إصدار الفاتورة","طابق كشف الراجحي مع الأستاذ العام","حدد أول نقطة اختلاف بين الكشفين","قارن حركة الأصناف وحدد الصنف الناقص","احسب الربحية الشهرية وحدد أشهر الربح والخسارة"];
const emptyAging=[
 {label:"0–30 يومًا",value:"0.00 ر.س",count:0,percent:"0%",tone:"ok"},
 {label:"31–45 يومًا",value:"0.00 ر.س",count:0,percent:"0%",tone:"info"},
 {label:"46–60 يومًا",value:"0.00 ر.س",count:0,percent:"0%",tone:"info"},
 {label:"61–90 يومًا",value:"0.00 ر.س",count:0,percent:"0%",tone:"warn"},
 {label:"91–120 يومًا",value:"0.00 ر.س",count:0,percent:"0%",tone:"warn"},
 {label:"أكثر من 120 يومًا",value:"0.00 ر.س",count:0,percent:"0%",tone:"bad"},
] as const;

export default function Home(){
 const input=useRef<HTMLInputElement>(null);const pendingAction=useRef("");const [files,setFiles]=useState<File[]>([]);const [message,setMessage]=useState("");const [active,setActive]=useState("مراجعة شاملة لكل الحسابات");const [accountType,setAccountType]=useState<"عميل"|"مورد">("عميل");const [creditDays,setCreditDays]=useState(60);const [result,setResult]=useState<AnalysisResult|null>(null);const [status,setStatus]=useState("");const [error,setError]=useState("");
 useEffect(()=>{const saved=Number(window.localStorage.getItem("mazaya-credit-days"));if(saved>=1&&saved<=365)setCreditDays(saved)},[]);
 async function analyzeFiles(next:File[],request:string,days=creditDays){if(!next.length)return;setStatus(`جارٍ إعداد تقرير: ${request}`);setError("");try{const data=await Promise.all(next.map(readAccountingFile));const report=analyzeData(request,data,days);setResult(report);setStatus("");pendingAction.current="";window.setTimeout(()=>document.getElementById("analysis-result")?.scrollIntoView({behavior:"smooth",block:"start"}),100)}catch(e){setStatus("");setError(e instanceof Error?e.message:"تعذر تحليل الملف. تأكد من أنه غير تالف وأن الأعمدة واضحة.");window.setTimeout(()=>document.getElementById("analysis-error")?.scrollIntoView({behavior:"smooth",block:"center"}),100)}}
 function applyCreditDays(raw:number){const days=Math.max(1,Math.min(365,Math.round(raw)||1));setCreditDays(days);window.localStorage.setItem("mazaya-credit-days",String(days));if(files.length&&result){const request=message||pendingAction.current||`مطابقة رصيد ${accountType} طبقًا لكشف الحساب`;void analyzeFiles(files,request,days)}}
 function choose(t:string){pendingAction.current=t;setMessage(t);setError("");if(files.length)void analyzeFiles(files,t,creditDays);else input.current?.click()}
 function matchAccountBalance(){const request=`مطابقة رصيد ${accountType} طبقًا لكشف الحساب`;pendingAction.current=request;setMessage(request);setActive(accountType==="عميل"?"العملاء وأعمار الديون":"الموردون والاستحقاقات");setError("");if(files.length)void analyzeFiles(files,request);else input.current?.click()}
 function handleFiles(list:FileList|null){const next=Array.from(list||[]);setFiles(next);setError("");const request=pendingAction.current||message||active||"مراجعة شاملة لكل الحسابات";if(next.length){if(!message)setMessage(request);void analyzeFiles(next,request)}}
 async function run(){if(!files.length){input.current?.click();return}await analyzeFiles(files,message||active)}
 const balanceSummary=result?.summary.find(item=>/الرصيد الختامي|صافي رصيد|إجمالي المستحق|اجمالي المستحق/.test(item.label));
 const closingBalance=result?.aging?.total||result?.conclusion?.value||balanceSummary?.value||(result?"غير متاح لهذا التقرير":"0.00 ر.س");
 const provisionalBalance=!!result?.conclusion?.detail.includes("مبدئي");
 const dashboardAging=result?.aging?.buckets||emptyAging;
 return <main className="shell">
  <aside><div className="logo"><b>م</b><div><strong>شركة مزايا</strong><span>لتقنية المعلومات</span></div></div><nav>{side.map((s,i)=><button onClick={()=>setActive(s)} className={active===s?"active":""} key={s}><i>{["⌂","▣","♙","♟","▤","▦","≡","▥","٪","↗","▥"][i]}</i>{s}</button>)}</nav><div className="secure">✓ وضع المراجعة الآمن<small>لا يتم تعديل قيود الـ ERP الأصلية</small></div></aside>
  <section className="page"><header><div><h1>{active}</h1><p>شركة مزايا لتقنية المعلومات · الفرع الرئيسي</p></div><button onClick={()=>input.current?.click()}>＋ رفع ملفات للتحليل</button></header>
   <div className="hero"><div className="ai">M</div><h2>المساعد المحاسبي لشركة مزايا لتقنية المعلومات</h2><p>ارفع كشوف Excel أو PDF وتقارير الـ ERP، واختر نوع المراجعة. سيقارن المساعد الحركات ويحدد الفروق والمتأخرات وتواريخ الاستحقاق ويجهز تقريرًا واضحًا للمحاسب.</p><div className="badges"><span>Excel</span><span>PDF</span><span>كشف بنك</span><span>تقرير ERP</span></div></div>
   <section className="balance-match"><div className="balance-match-copy"><span>تحليل الحساب والاستحقاق</span><h3>تحليل حساب العميل أو المورد وتحديد أعمار الذمم</h3><p>حدد نوع الحساب ومدة استحقاق فواتيره أولًا، ثم ارفع كشف الحساب. سيطابق النظام الرصيد ويخصم السداد من أقدم الفواتير ويعرض غير المستحق والمستحق الفعلي وأعمار الذمم.</p></div><div className="balance-match-controls"><div className="account-switch" role="group" aria-label="نوع الحساب"><button className={accountType==="عميل"?"active":""} onClick={()=>setAccountType("عميل")}>حساب عميل</button><button className={accountType==="مورد"?"active":""} onClick={()=>setAccountType("مورد")}>حساب مورد</button></div><div className="account-credit"><label htmlFor="account-credit-select">مدة استحقاق الفاتورة</label><select id="account-credit-select" value={[15,30,45,60,90,120].includes(creditDays)?creditDays:"custom"} onChange={e=>{if(e.target.value!=="custom")applyCreditDays(Number(e.target.value))}}><option value={15}>15 يومًا</option><option value={30}>30 يومًا</option><option value={45}>45 يومًا</option><option value={60}>60 يومًا</option><option value={90}>90 يومًا</option><option value={120}>120 يومًا</option><option value="custom">مدة مخصصة</option></select><input aria-label="مدة استحقاق مخصصة بالأيام" type="number" min={1} max={365} value={creditDays} onChange={e=>applyCreditDays(Number(e.target.value))}/></div><button className="match-now" onClick={matchAccountBalance}>رفع الكشف وتحليل أعمار الذمم</button><small>المدة المطبقة الآن: {creditDays} يومًا — عند تغييرها يُعاد التحليل تلقائيًا</small></div></section>
   <div className="cards">{actions.map(([t,d,ic])=><button key={t} onClick={()=>choose(t)}><i>{ic}</i><div><strong>{t}</strong><span>{d}</span></div><b>←</b></button>)}</div>
   <section className="due"><div className="due-heading"><div><h3>مدة استحقاق الحساب: {creditDays} يومًا</h3><p>اختر مدة الائتمان الخاصة بهذا العميل أو المورد؛ يبدأ الاستحقاق من اليوم {creditDays+1} بعد تاريخ الفاتورة</p></div><div className="due-days"><label htmlFor="due-days">عدد الأيام</label><input id="due-days" type="number" min={1} max={365} value={creditDays} onChange={e=>applyCreditDays(Number(e.target.value))}/></div></div><div className={`due-total ${result?"live":""}`}><span>الرصيد الختامي</span><strong>{closingBalance}</strong><small>{result?`مدة الاستحقاق المطبقة: ${creditDays} يومًا`:"حدد المدة ثم ارفع كشف الحساب"}</small></div><div className="due-grid">{dashboardAging.map(bucket=><article className={bucket.tone} key={bucket.label}><span>{bucket.label}</span><strong>{bucket.value}</strong><small>{result?.aging?`${bucket.count} بند · ${bucket.percent}`:result?"اختر تحليل عميل أو مورد لإظهار الأعمار":"بانتظار رفع الملف"}</small></article>)}</div></section>
   <section className="upload"><div className="paper">⇧</div><div><strong>{files.length?`تم اختيار ${files.length} ملف` : "اختر نوع التقرير ثم ارفع الملفات"}</strong><span>{message.includes("مطابقة كشف المورد")?"اختر كشف المورد أولًا ثم كشف حسابه من ERP — تبدأ المطابقة تلقائيًا":"يقرأ جميع أوراق Excel ويتحقق من الجداول قبل بدء التحليل"}</span>{files.length>0&&<small>{files.map(f=>f.name).join(" · ")}</small>}</div><button onClick={()=>input.current?.click()}>اختيار الملفات</button><input ref={input} type="file" multiple accept=".pdf,.xlsx,.xls,.xlsm,.xlsb,.ods,.csv,.txt" onChange={e=>{handleFiles(e.target.files);e.currentTarget.value=""}}/></section>
   <section className="composer"><div className="chips">{prompts.map(p=><button key={p} onClick={()=>{setMessage(p);pendingAction.current=p}}>{p}</button>)}</div><div className="box"><input value={message} onChange={e=>{setMessage(e.target.value);pendingAction.current=e.target.value}} placeholder="اكتب طلب المراجعة هنا... مثال: احسب الربحية الشهرية"/><button onClick={run} disabled={!!status}>{status?"جارٍ التحليل...":"إعداد التقرير"}</button></div>{status&&<div className="processing"><b>◌</b><div><strong>جارٍ قراءة البيانات وإعداد التقرير</strong><span>{status}</span></div></div>}{error&&<div id="analysis-error" className="error"><b>تعذر إعداد التقرير</b><span>{error}</span><button onClick={()=>input.current?.click()}>اختر ملفًا آخر</button></div>}<small>تتم معالجة الملفات داخل الصفحة ولا يُرحّل النظام أي قيد. راجع النتائج قبل الاعتماد.</small></section>
   {result?<ResultView result={result}/>:<section id="analysis-result" className="report-placeholder"><div>▥</div><h2>سيظهر تقرير التحليل هنا داخل الصفحة</h2><p>اختر نوع التحليل من المربعات، ثم ارفع الملف. لا يلزم طباعة التقرير أو تنزيله؛ يمكنك قراءة كل النتائج والجداول مباشرة من الواجهة.</p></section>} 
  </section>
 </main>
}

function reportRows(result:AnalysisResult){return [["التقرير",result.title],["درجة الثقة",result.confidence],...(result.conclusion?[["النتيجة النهائية",result.conclusion.label],[result.conclusion.label,result.conclusion.value],["توضيح",result.conclusion.detail]]:[]),...(result.dueScenarios?[["",""],["المستحق الفعلي حسب مدة الائتمان",""],...result.dueScenarios.items.map(item=>[item.label,item.value,item.selected?"المدة المختارة":""])]:[]),...(result.supplierFlow?[["",""],[result.supplierFlow.title,""],["مصدر الرصيد",result.supplierFlow.source],["معادلة الحساب",result.supplierFlow.equation],...result.supplierFlow.items.map(item=>[item.label,item.value,item.hint])]:[]),...(result.aging?[["",""],[result.aging.title,result.aging.total],["تاريخ القياس",result.aging.asOf],["أساس الاحتساب",result.aging.basis],["الفترة","المبلغ","عدد البنود","النسبة"],...result.aging.buckets.map(b=>[b.label,b.value,String(b.count),b.percent])]:[]),["",""],...result.summary.map(s=>[s.label,s.value]),["",""],["الملاحظات",""],...result.findings.map(f=>[f.title,f.detail]),...(result.dueTable?[["",""],["تفاصيل تواريخ الاستحقاق",""],result.dueTable.headers,...result.dueTable.rows]:[]),...(result.table?[["",""],result.table.headers,...result.table.rows]:[])]}
function reportText(result:AnalysisResult){return reportRows(result).map(r=>r.join(": ")).join("\n")}
function downloadReport(result:AnalysisResult){const csv="\ufeff"+reportRows(result).map(r=>r.map(c=>`"${String(c).replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`تقرير-${result.title}.csv`;a.click();URL.revokeObjectURL(url)}
function ResultView({result}:{result:AnalysisResult}){const [copied,setCopied]=useState(false);const needsReview=result.confidence==="محدودة"||result.conclusion?.tone==="bad";async function copy(){await navigator.clipboard.writeText(reportText(result));setCopied(true);window.setTimeout(()=>setCopied(false),1800)}return <section id="analysis-result" className="result">
 <div className={`report-ready ${needsReview?"needs-review":""}`}>{needsReview?"△ تم إعداد قراءة مبدئية — توجد بيانات تحتاج تأكيدًا قبل الاعتماد":"✓ تم إعداد التقرير بنجاح — راجع النتائج ثم اطبعها أو نزّلها"}</div>
 <div className="result-head"><div><span>تقرير المراجعة ظاهر داخل الصفحة</span><h2>{result.title}</h2><p>درجة الثقة في التعرف على الأعمدة: <b>{result.confidence}</b></p></div><div className="result-actions"><BalanceConfirmationButton result={result}/><button onClick={copy}>{copied?"تم نسخ النتائج ✓":"نسخ النتائج"}</button><button onClick={()=>downloadReport(result)}>تنزيل CSV</button><button onClick={()=>window.print()}>طباعة (اختياري)</button></div></div>
 {result.conclusion&&<div className={`result-conclusion ${result.conclusion.tone}`}><div><span>النتيجة النهائية</span><h3>{result.conclusion.label}</h3><strong>{result.conclusion.value}</strong></div><p>{result.conclusion.detail}</p></div>}
 {result.title==="مطابقة كشف البنك مع النظام"&&<BankReconciliationTools result={result}/>} 
 {result.dueSchedule&&<section className="due-cutoff"><div><span>قاعدة الرصيد عند آخر فاتورة مستحقة</span><h3>{result.dueSchedule.asOf}</h3>{result.dueSchedule.cutoffInvoiceDate?<p>فاتورة القطع: <b>{result.dueSchedule.cutoffInvoiceDate}</b> · رصيدها الجاري: <b>{result.dueSchedule.cutoffBalance}</b> · الخصومات اللاحقة: <b>{result.dueSchedule.laterDeductions}</b></p>:<p>لا توجد فاتورة وصل تاريخ استحقاقها حتى تاريخ القياس.</p>}</div>{result.dueSchedule.nextDueDate?<div className="next-due"><span>رصيد غير مستحق — أقرب استحقاق حسب تاريخ الفاتورة</span><strong>{result.dueSchedule.nextDueAmount}</strong><small>استحقاق {result.dueSchedule.nextDueCreditDays} يومًا بتاريخ {result.dueSchedule.nextDueDate} · متبقي {result.dueSchedule.nextDueDays} أيام · {result.dueSchedule.nextDueRef}</small></div>:<div className="next-due complete"><span>لا يوجد استحقاق قادم</span><strong>كل الفواتير المفتوحة دخلت حسب تاريخ القياس</strong></div>}</section>}
 {result.dueScenarios&&<section className="due-scenarios"><div className="due-scenarios-head"><span>المدة التعاقدية المختارة فقط</span><h3>الرصيد الفعلي المستحق من تاريخ إصدار الفاتورة</h3><p>تُعتمد مدة الحساب التي اخترتها لهذا المورد أو العميل فقط؛ ولا تظهر مدد 30 أو 45 أو 60 أو 90 أو 120 يومًا الأخرى كأنها استحقاقات فعلية.</p></div><div className="due-scenarios-grid">{result.dueScenarios.items.filter(item=>item.selected).map(item=><article className="selected" key={item.days}><span>{item.label}</span><strong>{item.value}</strong><small>✓ مدة الحساب المعتمدة لهذا الكشف</small></article>)}</div></section>}
 {result.supplierFlow&&<section className="supplier-flow"><div className="supplier-flow-head"><div><span>حساب المورد بصورة محاسبية واضحة</span><h3>{result.supplierFlow.title}</h3><p>{result.supplierFlow.note}</p></div><div><b>مصدر الصافي</b><strong>{result.supplierFlow.source}</strong></div></div><div className="supplier-equation">{result.supplierFlow.equation}</div><div className="supplier-flow-grid">{result.supplierFlow.items.map(item=><article className={item.tone} key={item.label}><span>{item.label}</span><strong>{item.value}</strong><small>{item.hint}</small></article>)}</div></section>}
 {result.aging&&<section className="aging-result"><div className="aging-head"><div><span>شرح استخراج الأرصدة</span><h3>{result.aging.title}</h3><p>كل خانة = مجموع الأرصدة المفتوحة المتبقية للفواتير التي يقع عمرها داخل الفترة. العمر = تاريخ القياس ناقص تاريخ إصدار الفاتورة. السداد والمردودات خُصمت من أقدم فاتورة أولًا (FIFO)، ثم جُمعت المبالغ المتبقية فقط. هذه الخانات توزيع للرصيد الختامي، أما المستحق الفعلي فيظهر منفصلًا حسب مدة {result.dueScenarios?.selectedDays||"الائتمان"} يومًا.</p></div></div><div className="aging-total"><span>مجموع الفئات = الرصيد الختامي</span><strong>{result.aging.total}</strong><small>حتى {result.aging.asOf}</small></div><div className="aging-buckets">{result.aging.buckets.map(bucket=><article className={bucket.tone} key={bucket.label}><span>{bucket.label}</span><strong>{bucket.value}</strong><small>ناتج جمع {bucket.count} فاتورة مفتوحة · {bucket.percent} من الرصيد</small></article>)}</div></section>}
 <div className="result-summary">{result.summary.map(s=><article className={s.tone||""} key={s.label}><span>{s.label}</span><strong>{s.value}</strong></article>)}</div>
 <div className="finding-grid">{result.findings.map((f,i)=><article className={f.tone} key={i}><b>{f.tone==="ok"?"✓":f.tone==="bad"?"!":f.tone==="warn"?"△":"i"}</b><div><strong>{f.title}</strong><p>{f.detail}</p></div></article>)}</div>
 {result.dueTable&&<section className="table-section"><div className="table-title"><div><span>تاريخ الفاتورة + المدة المختارة</span><h3>الفواتير المفتوحة وتحديد المستحق</h3></div><strong>{result.dueTable.rows.length} فاتورة</strong></div><div className="result-table"><table><thead><tr>{result.dueTable.headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{result.dueTable.rows.map((r,i)=><tr className={r.includes("مستحق")?"purchase-row":""} key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div></section>}
 {result.table&&<section className="table-section"><div className="table-title"><div><span>التفاصيل المحاسبية</span><h3>حركات ومستندات كشف الحساب</h3></div><strong>{result.table.rows.length} حركة</strong></div>{result.table.rows.length?<div className="result-table"><table><thead><tr>{result.table.headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{result.table.rows.map((r,i)=>{const text=r.join(" ");const rowClass=/مشتريات/.test(text)?"purchase-row":/مبيعات/.test(text)?"sale-row":/سداد|مرتجع|إشعار خصم/.test(text)?"payment-row":"";return <tr className={rowClass} key={i}>{r.map((c,j)=>{const isKind=result.table?.headers[j]==="نوع المستند",kindClass=isKind?`doc-kind ${/مشتريات/.test(c)?"purchase":/مبيعات/.test(c)?"sale":/سداد/.test(c)?"payment":/مرتجع/.test(c)?"return":/إشعار خصم/.test(c)?"discount":"unknown"}`:"";return <td className={kindClass} key={j}>{isKind?<span>{c}</span>:c}</td>})}</tr>})}</tbody></table></div>:<div className="empty-table"><b>لم تُقرأ حركات من الملف</b><span>تأكد أن صف عناوين الأعمدة يحتوي التاريخ والبيان والمدين والدائن أو الرصيد، ثم أعد رفع الملف.</span></div>}</section>}
 <div className="audit"><div><h3>فحوص وضوابط الاعتماد</h3>{result.checks.map(c=><p key={c}>✓ {c}</p>)}</div><div><h3>الملفات المصدر</h3>{result.sources.map(s=><p key={s}>▤ {s}</p>)}</div></div>
 </section>}
